"""empty message

Revision ID: 422bce70433e
Revises: a0e5780bb44d
Create Date: 2023-06-05 22:54:50.725770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422bce70433e'
down_revision = 'a0e5780bb44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_favorites',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Starship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Starship_id'], ['starship.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_favorites')
    # ### end Alembic commands ###
