"""empty message

Revision ID: a0e5780bb44d
Revises: fda74c8172b6
Create Date: 2023-06-05 02:02:05.690396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e5780bb44d'
down_revision = 'fda74c8172b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pl_favorites',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], )
    )
    op.create_table('ch_favorites',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], )
    )
    op.drop_table('Favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorites',
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], name='Favorites_Character_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], name='Favorites_User_id_fkey')
    )
    op.drop_table('ch_favorites')
    op.drop_table('Pl_favorites')
    # ### end Alembic commands ###
