"""empty message

Revision ID: fda74c8172b6
Revises: 2dd7bff23e8c
Create Date: 2023-06-03 01:39:39.312445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda74c8172b6'
down_revision = '2dd7bff23e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorites',
    sa.Column('User_id', sa.Integer(), nullable=True),
    sa.Column('Character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Favorites')
    # ### end Alembic commands ###
